CREATE TABLE IF NOT EXISTS tbl_user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tbl_media (
    id SERIAL PRIMARY KEY,
    url VARCHAR(1024) NOT NULL,
    title VARCHAR(80) NOT NULL,
    userId INTEGER NOT NULL,
    created TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (userId) REFERENCES tbl_user(id)
);

CREATE TABLE IF NOT EXISTS tbl_favourites (
    id SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL,
    mediaId INTEGER NOT NULL,
    FOREIGN KEY (userId) REFERENCES tbl_user(id),
    FOREIGN KEY (mediaId) REFERENCES tbl_media(id) ON DELETE CASCADE
);
